# Generated by Django 3.0.7 on 2020-07-25 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(default='', help_text='The tile of the event', verbose_name='Event Name')),
                ('event_location', models.TextField(default='', help_text='The location of the event', verbose_name='Event Location')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='The date the event will be on', verbose_name='Event date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, help_text='The date the event will be on', verbose_name='Event date')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, help_text='The time the event will start', verbose_name='Starting time')),
                ('end_time', models.TimeField(default=datetime.datetime(2020, 7, 25, 15, 7, 19, 640407, tzinfo=utc), help_text='The time the event will end', verbose_name='Final time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
